### ISSUE TITLE
We need a Game

### ISSUE THREAD

**Issue by natt8** [cs361-W16/Group16#7]
so that the deck and board can be implemented together

**Comment by alecno20** [comment]
Good Idea ill make that right now!

**Comment by alecno20** [comment]
I finished If you would like to merge my pull request!!!!!!!

**Comment by natt8** [comment]
I was supposed to make a game. So I don't know what to do now. My deal was taken too so I haven't implemented anything yet. Do I need to accept the pull request?

**Comment by alecno20** [comment]
okay so we have a deal thing but it doesnt pass to the game. So if you merge mine you can add a 2d array to game representing the board and then have it pass cards from the deal command to the board

**Comment by ghost** [comment]
you can re-write the deal function if you want. There are a few features
you could add. For instance, it could copy the remaining deck to a new one
so that we didn't have null values at the end of the array (you'd have to
modify the remove() function to do that).

But if the game/board/deck classes are already made, you could also start
working on the Views/Controller part of MVC so that the game actually
interacts with the user. I'm going to stop working on the project until you
have something you're comfortable committing. Once you are ready to issue a
pull request let me know and I will approve it (since i'm the only one who
hasn't approved one).
